name: Android Release Build Deploy To Firebase App Distribution
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Android Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidDemo.apk
          path: app/debug/app-debug.apk

#      - name: Upload Artifact to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
#        with:
#          appId: ${{ secrets.FIREBASE_APP_ID }}
#          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
#          groups: 'testers'
#          file: app/build/outputs/apk/release/app-release.apk
#          debug: false
